### ISSUE TITLE
Vercel Platforms: image upload broken / assets subdomain variable

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1127]
The image upload tool is now working, but the images are being loaded from a hardcoded assets subdomain. To do: set this in an `ASSETS_DOMAIN` env var and remove the hardcoded domain from the couple of places it's being used.

Better yet, replicate the cloudfront settings we use for [assets.tinynewsco.org](http://assets.tinynewsco.org/) to host staging images at [assets.tinynewsco.dev](http://assets.tinynewsco.dev/)

**Comment by jacqui** [comment]
This is fixed, with one caveat: I think that `assets.tinynewsco.org` needs to be updated for the staging bucket... but that might be tricky to accomplish before we roll out the updated Platforms migration.

Image uploads work, but you get an access denied when trying to display them using the assets url instead of the s3 bucket url.

**Comment by jacqui** [comment]
To-do: setup the assets.tinynewsco.dev DNS and then add it as an alternate domain name (CNAME) to [the new cloudfront distro](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/distributions/E1AE0PLPZ4Q05M).

Instructions from AWS:

```
To add an alternate domain name (CNAME) to a CloudFront distribution, you must attach a trusted certificate that validates your authorization to use the domain name. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements
```
