### ISSUE TITLE
Vercel Platforms: Deployed TinyCMS pages cause 500 error

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1129]
https://harveyworld.tinynewsco.dev/tinycms
https://blackbygod.tinynewsco.dev/tinycms

**Comment by jacqui** [comment]
This was due to the settings table not yet loaded with data for all the orgs, plus the Google Credentials missing the full set of redirect urls & authorized domains (blackbygod.tinynewsco.dev, etc). I've populated both the table and the google settings.

I was then able to login to each org's tinyCMS with my newscatalyst email:

* https://blackbygod.tinynewsco.dev/tinycms
* https://fivewardsmedia.tinynewsco.dev/tinycms
* https://harveyworld.tinynewsco.dev/tinycms
* https://spotlightschools.tinynewsco.dev/tinycms
* https://austin-vida.tinynewsco.dev/tinycms
* https://angdiaryo.tinynewsco.dev/tinycms
