### ISSUE TITLE
Build error: a required parameter (category) was not provided as a string in getStaticPaths for /articles/[category]/[slug]

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#162]
Maybe something busted in the database?

**Comment by jacqui** [comment]
Yeah - something was busted in the database. 3 articles didn't have a category because the sidebar menu was using an old, invalid cached list of categories.

I fixed this - https://github.com/news-catalyst/google-app-scripts/pull/113 - and republished the articles. All good now.

Thing is, category is required in the sidebar, so this shouldn't happen in the future provided we have a stable API - which, of course, we should!
