### ISSUE TITLE
Building out i18n support

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#170]
This is a bigger issue that touches more of the stack, but is made more possible by #169 

Next.js 10 has better i18n support with [internationalized routing](https://nextjs.org/blog/next-10#internationalized-routing), so we should support that. More importantly, we need to connect webiny's locales to the next.js build. And we need to be able to put content in at different locales, which doesn't really touch this repo. This is a big chunk of work that's likely worth its own sprint (or two!) Just to spell it all out in one place:

- An article should be able to store content in multiple languages via Webiny's locales feature. (From multiple Google Docs? Multiple languages in the same doc? How do we handle this?)
- The next.js build should be able to request article data for multiple locales if necessary, and build out each article page for each locale (how does next.js know what locales a specific website supports?)
- Site metadata should also be translatable, such as newsletter prompts, donation asks, etc.

**Comment by jacqui** [comment]
> * An article should be able to store content in multiple languages via Webiny's locales feature. (From multiple Google Docs? Multiple languages in the same doc? How do we handle this?)

I think we should use multiple docs for the article, one in each language/locale. Otherwise specifying which parts belong to which language can get wild... this could be a google doc management nightmare though. We could suggest one folder per article on sites where there's more than one (or maybe two?) languages? I have a feeling most sites will be bilingual at most though. Special cases that come to mind are way bigger than a TNC (like the BBC; even the NYT only does multi languages on very select articles).

> * The next.js build should be able to request article data for multiple locales if necessary, and build out each article page for each locale (how does next.js know what locales a specific website supports?)

Okay this is technically doable by having next.js list locales from the webiny API for the TNC site.

<img width="1329" alt="Screen Shot 2020-10-28 at 7 20 07 am" src="https://user-images.githubusercontent.com/3397/97357537-0af45580-18ee-11eb-9164-237d7f457dd4.png">

> * Site metadata should also be translatable, such as newsletter prompts, donation asks, etc.

So long as these are set up in the model and graphql as i18nstrings we should be good there (but needs verifying).

Also, of course, we need to make sure we're asking "which language?" content is in instead of assuming the default one across the board. I'm pretty sure I've code stuff with the assumption instead of the question in several places... but hey at least it's a variable? :)
