### ISSUE TITLE
tinycms & deleting content

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#290]
this came up in PR #289 - do we want to allow deleting content from the tinycms? if yes, which content? for instance, deleting a section could be problematic as they're required for articles to be saved & to load (section slug is part of the url). 

this doesn't seem urgent but thought I'd flag it.

also: I'm building in a `published` flag on all content in hasura, defaulting this value in the DB to `false` and secretly setting it to `true` when you do things in the tinycms like "create a section" or "update an author" - perhaps we should be a bit more forthcoming about this? that is, do we need / want to surface "save as draft" + "publish" functionality in the tinycms for content?

**Comment by TylerFisher** [comment]
This is a good question.

I think we definitely shouldn't allow people to delete sections from the database since that would break existing articles. I think you could "unpublish" sections though, that way they'd come out of the navbar, but the article page with the old category could still get built.

I don't see a compelling reason to offer draft sections or authors. No reason to make that more complicated than necessary.

**Comment by jacqui** [comment]
Okay, thanks for clarifying. This makes sense. I'll log an issue here to make sure I:

* add ability to unpublish a section
* ensure the nav only includes published sections (you may have done this already but i will check)
* ensure an article page can get built when its category is `published: false`
