### ISSUE TITLE
We can't use Bulma because of AMP :(

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#31]
Thus, we're gonna have to do a pretty serious CSS rewrite from scratch. Yay.

**Comment by jacqui** [comment]
Argh. Yeah I just stumbled across this issue when trying to build the site locally prior to deploying with vercel. I don't think I can successfully deploy it if it won't even build locally.

Seems like the issue is that AMP doesn't allow external CSS loading/importing, which we're doing with bulma. I'm not sure how far you got, @TylerFisher , but perhaps we can use something like [purgecss](https://github.com/FullHuman/purgecss) to filter out the bits of bulma we're actually using, then inline the CSS? I found people seem to be doing this for AMP compatibility with bulma and various other CSS libraries...

**Comment by jacqui** [comment]
Yeah I was right - vercel deploy fails because of this issue:

```

/?amp=1  error  CSS syntax error in tag 'style amp-custom' - saw invalid at rule '@import'.
--


```

I'm going to try the purgecss approach. Considering this is "just" a demo site, right, it wouldn't be ideal to have to rewrite all of the CSS just to get it working for AMP? We'll see how I go.

**Comment by jacqui** [comment]
I'm closing this issue as I managed a workaround for bulma :) Also the site is deployed on vercel (separate issue) https://next-tinynewsdemo.vercel.app/ 🌟
