### ISSUE TITLE
Rethink the getStaticPaths query for articles

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#335]
I can't quite put my finger on how to replicate this exactly, but this query seems like it should have a few more conditions:

```
const HASURA_LIST_ARTICLE_SLUGS = `query MyQuery {
  articles {
    slug
    article_translations(where: {published: {_eq: true}}) {
      locale_code
    }
    category {
      slug
    }
  }
}`;
```

We should be only checking for articles with published translations?

This also likely doesn't matter because of how the loop is constructed. An article with an empty translations array just wouldn't get added to `paths`:

```
  let paths = [];
  for (const article of data.articles) {
    for (const locale of article.article_translations) {
      paths.push({
        params: {
          category: article.category.slug,
          slug: article.slug,
        },
        locale: locale.locale_code,
      });
    }
  }
```
 But over time, we could be transmitting way more data than we need to in this query.

Also, `orgSlug` is commented out when calling the request, but I'm not sure if that's intentional for some reason?

```
export async function hasuraListAllArticleSlugs() {
  return fetchGraphQL({
    url: process.env.HASURA_API_URL,
    orgSlug: process.env.ORG_SLUG,
    // url: params['url'],
    // orgSlug: params['orgSlug'],
    query: HASURA_LIST_ARTICLE_SLUGS,
    name: 'MyQuery',
  });
}
```

**Comment by jacqui** [comment]
You're right, this definitely needs fixes.

I think the query to retrieve all published articles for all locales should be:

```
query MyQuery {
  articles(where: {article_translations: {published: {_eq: true}}}) {
    slug
    article_translations(where: {published: {_eq: true}}, distinct_on: locale_code) {
      locale_code
      published
    }
    category {
      slug
    }
  }
}
```

This will retrieve only articles with published translations (instead of returning some with empty translation arrays), and then at most one entry per article per locale (the distinct helps here). 

Then the loop will only be iterating over article pages that should be published in the first place, once per locale + article. 

There should only be one organization slug param passed to retrieve via graphql; I removed the commented out lines as they don't belong.
