### ISSUE TITLE
Analytics dashboard

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#392]
This will likely expand into many issues, but I'm writing down the bigger plan here.

We want a custom analytics dashboard in the TinyCMS that pulls from Google Analytics (and maybe more sources in the future). On first pass, it should display:

## Sessions and views
- Sessions
- Most popular pages by views
- Time on site average
- Sessions by audience segment (defined as custom dimensions: donor, subscriber, frequent reader, unknown)
- Most popular pages for each audience segment
- Sessions by geographical segment (are you reaching your community?)
- Sessions by referrer (search, social, direct, etc.)

## Newsletter subscription
- Views over past 30 days
- Subscriptions over past 30 days
- Conversion rate over past 30 days
- Most popular pages for newsletter subscriptions over past 30 days (i.e., what stories are converting?)
- Newsletter subscriptions by audience segment (i.e., what types of users are converting? Donors? Frequent readers?)

## Donations
- Donation button clicks
- Most popular pages for donation clicks over past 30 days (i.e., what stories are converting?)
- Donation button clicks by audience segment (i.e., what types of users are converting? Newsletter subscribers? Frequent readers?)
- TBD what we can get back from MonkeyPod, but hopefully we can follow through to the checkout process as well.

## Reading depth
- Overall reading depth averages (we have events firing for every quarter of a story page)
- Most-read stories (highest percentage of 100% depth events)

**All of this data should be accessible for yesterday, the past week, and the past 30 days.**

We'll access all of this data through the [Analytics Reporting API](https://developers.google.com/analytics/devguides/reporting/core/v4). Our TinyCMS pages should server-side render so we can fetch this data on demand.

**Comment by jacqui** [comment]
* reading frequency: currently [calculated in the app as number of articles read in the last 30 days](https://github.com/news-catalyst/next-tinynewsdemo/blob/16f2d3e30a91691443e4867eee0d173c8addf047/lib/hooks/useAnalytics.js#L41-L73) and [stored in GA](https://github.com/news-catalyst/next-tinynewsdemo/blob/master/pages/_app.js#L36-L41) as `dimension2`

**Comment by jacqui** [comment]
Since I've just set up some custom dimensions in the GA account that our demo is using (GA_TRACKING_ID `UA-166777432-1` at https://analytics.google.com/analytics/web/#/a166777432w232819995p218630656/admin/custom-dimensions/m-content-dimensionsContent.rowShow=10&m-content-dimensionsContent.rowStart=0&m-content-dimensionsContent.sortColumnId=index&m-content-dimensionsContent.sortDescending=false&m-content.mode=LIST) I thought I'd document them:

### Custom Dimensions

|Name|Scope|Dimension Key|
|Contact Email|User|dimension1|
|Contact 30 Day Reading|Hit|dimension2|
|Contact Member Level|User|dimension3|
|Donor|User|dimension4|
|Subscriber|User|dimension5|
