### ISSUE TITLE
Preview a post?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#47]
Next supports a [preview mode](https://nextjs.org/docs/advanced-features/preview-mode). Does Webiny's API allow you to access draft data this way?

**Comment by jacqui** [comment]
Hrm... I know we can access that data by using the "admin" version of the API (`/cms/manage/production`) instead of the read-only "live" version.

The google docs add-on sidebar uses the "admin" content delivery api. Perhaps we could build something that connects the sidebar with a preview version of the app?

**Comment by jacqui** [comment]
Perhaps:

* google add-on sidebar has two buttons: `preview` + `save & publish`
* clicking `preview` merely constructs the front-end preview URL and opens it in a new browser window/tab
* preview.js will require a small change: look up the article in the admin API (has draft data)
  * note: this will also require storing the admin API url and a different access token for it
* at this point I'm a little unsure: I think we'd need to maintain two article templates tbh because the current article template expects to find the content in the read-only API
* `save & publish` keeps the same functionality

**Comment by TylerFisher** [comment]
Generally I think that approach is right. As far as component structure, we could just have wrapper components that are basically the same in that they would call an `<Article>` component, so there's not too much duplication. We could even keep the same API functions and just make the actual API URL a parameter.

Pseudocode example:

```
// article/preview.js
export default function PreviewArticle(props) {
  return (<Article {...props} />);
}

export async function getStaticProps({ params }) {
  const article = await getArticleBySlug(params.slug, process.env.PREVIEW_API_ROUTE)
  ...
}
```

```
// lib/articles.js
export async function getArticleBySlug(slug, apiUrl) {
  const webinyHeadlessCms = new GraphQLClient(apiUrl, {
    headers: {
      authorization: CONTENT_DELIVERY_API_ACCESS_TOKEN,
    },
  });
  ...
}

**Comment by jacqui** [comment]
Good idea! Okay, I'll try to wrap this up today.

**Comment by jacqui** [comment]
Okay, I ended up spending today getting the preview feature finished for the add-on. It was a little complicated, but I got through it 💪 (pr opened). I am able to click "preview" in the sidebar and end up with a new browser tab opened to the right preview-url, draft saved in webiny. Next up: actually pull the draft data and do these component changes.
