### ISSUE TITLE
Set up comments server again

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#660]
Comments haven't been turned on for a while. It's probably time to get that established again.

**Comment by jacqui** [comment]
I spent part of the afternoon getting back up to speed with Coral Talk. they no longer support the simple "click to deploy to heroku" button  (it's been removed from the Talk repo). They also explicitly do not include any instructions on how to deploy or run the app in production 🤔 

So, for next week, I need to sort out a plan for how we can best deploy, host & manage coral talk for the initial set of sites using docker.

**Comment by jacqui** [comment]
It looks like we can use a github action to deploy the coral talk app to Heroku. I haven't done this with docker-compose before, but there's an action already written to do it:

* https://github.com/marketplace/actions/deploy-multiple-docker-images-to-heroku-apps

If that doesn't work, I will try the more popular [deploy-to-heroku](https://github.com/marketplace/actions/deploy-to-heroku) action, though it seems to support single dockerfiles instead.

**Comment by jacqui** [comment]
Progress: I have Coral Talk mostly deployed to Heroku. Current issue: the app won't start due to a lack of language setup that I'm trying to debug. Error (viewable by doing `heroku logs -a coral-talk-dev`) is:

```
2021-07-12T04:16:20.558586+00:00 app[web.1]: {"name":"coral","hostname":"1ef25832-780f-4bc7-abad-aa43b45c0179","pid":3,"level":50,"err":{"message":"invalid language code: .wh..wh..opq","name":"Error","stack":"I18n.load (src/core/server/services/i18n/index.ts:47:17)\nServer.connect (src/core/server/index.ts:221:5)\nbootstrap (src/index.ts:51:5)\n"},"msg":"can not bootstrap server","time":"2021-07-12T04:16:20.556Z","src":{"file":"/usr/src/app/src/index.ts","line":59,"func":"bootstrap"},"v":0}
```

Links:

* [Heroku Dashboard for coral-talk-dev](https://dashboard.heroku.com/apps/coral-talk-dev/)
* [Docker Hub Image](https://hub.docker.com/r/coralproject/talk/)
* [Guide to Heroku Docker Deployment](https://devcenter.heroku.com/articles/container-registry-and-runtime)
* [MongoDB Atlas Cluster for coral-talk-dev](https://cloud.mongodb.com/v2/60ebb87b332e6b66747de424#clusters/connect?clusterId=Cluster0)
* [Deployed Coral Talk Admin link](https://coral-talk-dev.herokuapp.com/) - note this currently displays an error page because it's failing to bootstrap (language issue, mentioned above).

**Comment by jacqui** [comment]
Update: I managed to get coralproject/talk:6 docker version running without docker-compose on localhost without a problem. (you can't use docker-compose on heroku afaik, hence trying to do this locally.) I deployed the same docker image version to heroku - I was using `:latest` instead of `:6` - but unfortunately I'm getting the same error as I reported above related to 'invalid language code'.

I'm not seeing a database specific error in the heroku logs, but I'm wondering if there's some issue connecting to the hosted mongo atlas cluster. I'm going to try to running the docker container locally using the hosted mongo connection string instead of localhost and see what happens 🤞

**Comment by jacqui** [comment]
Yes! Coral Talk is setup on an ECS cluster in Amazon running behind a load balancer... the URL is:

http://coral-talk-lb-1654697893.us-east-1.elb.amazonaws.com/admin/login
