### ISSUE TITLE
Ids returned from homepage layout don't match story IDs

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#74]
For this homepage layout:

<img width="435" alt="Screen Shot 2020-08-17 at 2 08 18 PM" src="https://user-images.githubusercontent.com/1077075/90429141-1e37a900-e093-11ea-9ed2-a8467cdfea25.png">

The data structure the following IDs stored:

<img width="717" alt="Screen Shot 2020-08-17 at 2 10 37 PM" src="https://user-images.githubusercontent.com/1077075/90429294-71116080-e093-11ea-8616-c2a3c282330f.png">

However, when I request the articles themselves, I get different IDs from the articles:

<img width="766" alt="Screen Shot 2020-08-17 at 2 11 27 PM" src="https://user-images.githubusercontent.com/1077075/90429350-8edec580-e093-11ea-9090-45ea53b68d74.png">

My fear is that using the manage API and read APIs return different IDs. The quick fix here is to always use slugs. But this is strange behavior.

**Comment by jacqui** [comment]
So it looks like the discrepancy between the stored IDs in the homepage layout data and the actual article IDs is due to reversioning.

Here's an example stored homepage layout from before I saved many versions of a few articles yesterday while debugging the add-on:

<img width="901" alt="Screen Shot 2020-08-18 at 9 49 57 am" src="https://user-images.githubusercontent.com/3397/90455091-6a88f480-e138-11ea-9bfa-fa7bea91fc94.png">

I did a graph query for that ID and found it belonged to a previous version of the article - this data is accessible in the admin/manage version of the API:

<img width="1410" alt="Screen Shot 2020-08-18 at 9 50 17 am" src="https://user-images.githubusercontent.com/3397/90455131-8ab8b380-e138-11ea-9f67-b426e907ebb6.png">

You can see in the screenshot above that the latest published version has a different ID.

So I think it's good that we're using the slug now instead. I've [added an index](https://d1tj6tnba0qfzt.cloudfront.net/admin/cms/content-models/5f2a02d3f2a2b300079e06ae) on it to make it queryable, and I think 🙏 that means it's also unique. I tried to verify that in webiny docs + slack but didn't find any info.
