### ISSUE TITLE
Author pages

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#86]
The simplest version of this is just querying on the byline and listing articles by that author. A more robust version is creating an author model so we can include social handles, a bio, a title, a photo, etc. How hard do you think the robust version is?

Hardest thing, I imagine, would be having a place to define authors.

For an author model, the necessary fields are:

- Name
- Title
- Bio (long text)
- Twitter handle (what about other social? do people do that?)
- Photo
- Staff (boolean, so we could add contributors/freelancers without adding them to a staff page, for example)

**Comment by jacqui** [comment]
You're right - figuring out where to actually define all this is the hard part. The rest, not so much.

What if our homepage editor was part of a slim site configuration tool that included:

* setting the homepage layout & featured articles
* defining authors
* specifying other settings like default page title, icons, etc.?

Defining the authors would populate them in Webiny, and the sidebar in google docs could request the list of authors for a dropdown (single or multiple?) instead of, or in addition to, using the free text field for byline.

**Comment by TylerFisher** [comment]
Yeah, I think this is right. Then we can edit sitewide metadata stuff too. This could even handle #87 if we want.

**Comment by jacqui** [comment]
PR open for part of this feature - author content management - in another repo https://github.com/news-catalyst/tinynews-homepage-editor/pull/30
