### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#87]
Publications will need an about page that explains who they are, what they cover, etc. If we create more robust author modeling, we could list the staff as well.

We will need a place for publications to write their about page. Could be a specially-designated Google Doc, or somewhere else.

**Comment by jacqui** [comment]
I feel like this should be a specially designated google doc in order to leverage the editing tools google docs provides. Though I will absolutely admit that writing more functionality for a google docs add-on doesn't exactly fill me with joy, it's probably better for the product. 

If we made this part of a "tiny news editor" (my new name for https://github.com/news-catalyst/tinynews-homepage-editor), how would the editing work? We'd have to handle paragraph breaks, links, text formatting, and so on 😬 

We haven't discussed what the Google Docs setup looks like for each tiny news co. Maybe we could start with two top-level folders:

* articles
* pages

All articles go in the first folder; maybe it starts off with an example we provide?

The second folder would start with one document: `About`

I have a feeling that second folder will need more pages, though I'm not sure what they are yet (contact, privacy, ...?)

Each page in the second folder would map to a URL, so `About` -> `/about` and so on. Each would use a slightly modified function in the existing add-on to publish (so the `slug` would be hardcoded, but the text parsing would be the same).

Does this seem reasonable?

**Comment by jacqui** [comment]
Progress so far:

* [ ] determine google doc document "type" - is it an article or a regular page for the site?
* [ ] store the doc's type in document properties
* [ ] hide article-specific form sections in the sidebar for 'page' documents: so far article authors and custom byline
* [ ] create a content model in webiny for static pages; proposal is `Page` with fields `headline` and `content`
* [ ] call `createPage` and `createPageFrom` instead of `createBasicArticle` and `createBasicArticleFrom` when saving page content
* [ ] ensure preview works (related: how do we handle previewing static pages in the front-end; probably needs some work)
* [ ] ensure publish works
* [ ] review form fields available for static pages in the sidebar: do we need or want things like 'tags' and 'category/section' for these?
