### ISSUE TITLE
If image nodes are paired with text nodes, we should still display the text

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#994]

**Comment by jacqui** [comment]
So this is related to https://github.com/news-catalyst/google-app-scripts/pull/380 which fixes how the Doc is parsed for elements: images, main image, lists, embeds, text, etc. The big change is: whenever an image is found, it is pushed up to its own top level element instead of included in a list along with text elements. This means image and text nodes should never be paired up for the front-end to sort out. They should be separate.
